config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='blog/'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('easylearn.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^blog/', include('easylearn.blog.urls', namespace='blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

easylearn/blog/urls.py
from django.urls import include, path
from blog.views import BlogPostCreateView, BlogPostDetailView, BlogPostFeedListView, RecommendedBlogPostsListView, rate_view, comment_view, preview_view
app_name = 'blog'

urlpatterns = [
    path('write/', BlogPostCreateView.as_view(), name='write'),
    path('post/<int:pk>/',BlogPostDetailView.as_view() , name='blog_post'),
    path('post/<slug:slug>/',BlogPostDetailView.as_view() ,name='blog_post_slug'),
    path('',BlogPostFeedListView.as_view() , name='feed'),
    path('recommended/',RecommendedBlogPostsListView.as_view() , name='recommended'),
    path('<int:pk>/rate/<int:value>/',rate_view,name='rate'),
    path('<int:pk>/comment/', comment_view, name='comment'),
    path('preview/', preview_view, name='preview'),
]

easylearn/users/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from blog.views import follow_view, unfollow_view 

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    path(
        '<slug:username>/follow/',
        follow_view,
        name='follow'
    ),
    path(
        '<slug:username>/unfollow/',
        unfollow_view,
        name='unfollow'
    )
    
]

easylearn/blog/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from markdown import markdown
from slugify import UniqueSlugify
from bs4 import BeautifulSoup

POST_SUMMARY_LENGTH = 250

def check_unique_slug(text, *args):
    return not BlogPost.objects.filter(slug=text).exists()

# Create your models here.
class BlogPost(models.Model):
    """Model definition for BlogPost."""

    title = models.CharField(max_length=50, blank = False)
    slug = models.SlugField(blank=True)
    text = models.TextField(blank=False, max_length=4000)
    writer = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=False)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Meta definition for BlogPost."""

        verbose_name = 'Blog post'
        verbose_name_plural = 'Blog posts'
        ordering = ['-create_date']

    def __str__(self):
        """Unicode representation of BlogPost."""
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            unique_slugify = UniqueSlugify(unique_check=check_unique_slug)
            self.slug = unique_slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:blog_post_slug', kwargs={'slug': self.slug})

    def get_summary(self):
        soup = BeautifulSoup(self.get_summary_as_markdown())
        summary = soup.text[:POST_SUMMARY_LENGTH]
        if len(self.text) > POST_SUMMARY_LENGTH:
            summary += '...'
        return summary
    
    def get_summary_as_markdown(self):
        return markdown(self.text)

    def get_rating_avg(self):
        result = self.Ratings.aggregate(models.Avg('value'))['value__avg']
        if not result:
            return 0
        return result


class Comment(models.Model):
    """Model definition for Comment."""

    post = models.ForeignKey(BlogPost, models.CASCADE, blank=False)
    text = models.TextField(max_length=500, blank=False)
    create_date = models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=False)

    class Meta:
        """Meta definition for Comment."""

        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ['-create_date']

    def __str__(self):
        """Unicode representation of Comment."""
        return self.text



class Rating(models.Model):
    """Model definition for Rating."""

    rate_date = models.DateTimeField(auto_now_add=True)
    rater = models.ForeignKey('users.User', on_delete=models.CASCADE)
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='Ratings')
    value = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        blank=False
    )

    class Meta:
        """Meta definition for Rating."""

        verbose_name = 'Rating'
        verbose_name_plural = 'Ratings'
        unique_together = ("rater", "post")

    def __str__(self):
        """Unicode representation of Rating."""
        return '{} rates {} with {} start'.format(self.rater, self.post, self.value)


class Following(models.Model):
    """Model definition for Following."""

    follower = models.ForeignKey('users.User', on_delete=models.CASCADE, 
    related_name='followed')
    followed = models.ForeignKey('users.User', on_delete=models.CASCADE,
    related_name='followers')

    class Meta:
        """Meta definition for Following."""

        verbose_name = 'Following'
        verbose_name_plural = 'Followings'
        unique_together = ("follower", "followed")

    def __str__(self):
        """Unicode representation of Following."""
        return '{} follows {}'.format(self.follower, self.followed)
    

easylearn/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

easylearn/blog/forms.py
from django import forms

from blog.models import BlogPost

class BlogPostForm(forms.ModelForm):
    """BlogPostForm definition."""
    text = forms.CharField(widget=forms.Textarea(attrs={'cols':100, 'class':'arabic-text', 
    'id':'post-text'}), 
    max_length=4000, required=True, label='المنشور')
    title = forms.CharField(widget = forms.TextInput(attrs={'cols':50, 'class':'arabic-text'}),
     max_length=50, required=True, label='العنوان')

    class Meta:

        model = BlogPost
        fields = ('title', 'text',)

easylearn/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseBadRequest

from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.forms import BlogPostForm
from blog.models import BlogPost, Following, Rating, Comment
from easylearn.users.models import User

from markdown import markdown


class BlogPostCreateView(LoginRequiredMixin, CreateView):
    form_class = BlogPostForm
    template_name = "blog/write.html"
    success_url = ''

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super(BlogPostCreateView, self).form_valid(form)


class BlogPostDetailView(LoginRequiredMixin, DetailView):
    model = BlogPost
    template_name = "blog/post_details.html"
    pk_url_kwarg = 'pk'
    slug_url_kwarg = 'slug'
    query_pk_and_slug = True

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        user = self.request.user
        try:
            rating = Rating.objects.get(rater=user, post=self.object)
        except Rating.DoesNotExist:
            rating_val = -1
        else:
            rating_val = rating.value
        context['rating'] = rating_val
        return context


class BlogPostFeedListView(LoginRequiredMixin, ListView):
    model = BlogPost
    template_name = "blog/post_feed.html"
    paginate_by = 10

    def get_queryset(self):
        user = self.request.user
        followed_ids = user.followed.all().values_list('followed', flat=True)
        queryset = BlogPost.objects.filter(writer__in=followed_ids)
        return queryset


class RecommendedBlogPostsListView(LoginRequiredMixin, ListView):
    model = BlogPost
    #template_name = "TEMPLATE_NAME"


@login_required
def follow_view(request, username):
    curent_user = request.user
    other_user = User.objects.get(username=username)
    if Following.objects.filter(follower=curent_user, followed=other_user).exists():
        return HttpResponseRedirect(other_user.get_absolute_url())

    following = Following(follower=curent_user, followed=other_user)
    following.save()
    return HttpResponseRedirect(other_user.get_absolute_url())


@login_required
def unfollow_view(request, username):
    curent_user = request.user
    other_user = User.objects.get(username=username)
    following = Following.objects.filter(follower=curent_user, followed=other_user)
    if not following.exists():
        return HttpResponseRedirect(other_user.get_absolute_url())

    following.delete()
    return HttpResponseRedirect(other_user.get_absolute_url())

@login_required
def rate_view(request, pk, value):
    user = request.user
    rating = None
    try:
        rating = Rating.objects.get(rater=user, post=pk)
    except Rating.DoesNotExist:
        rating = Rating(rater=user, post=BlogPost.objects.get(pk=pk))
    rating.value = value
    rating.save()
    return redirect(BlogPost.objects.get(pk=pk))

@login_required
def comment_view(request, pk):
    user = request.user
    post = get_object_or_404(BlogPost, pk=pk)
    try:
        text = request.POST['text']
    except KeyError:
        return HttpResponseBadRequest()
    comment = Comment(writer=user, post=post, text=text)
    comment.save()
    return redirect(post)

@login_required
def preview_view(request):
    if request.method != 'POST':
        return HttpResponseBadRequest()
    try:
        text = request.POST['text']
    except KeyError:
        return HttpResponseBadRequest()
    html_text = markdown(text)
    return render(request, 'blog/preview.html',{'text':html_text})

easylearn/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User
from blog.models import Following

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add a boolean indicator of user following
        user = self.request.user
        context['followed'] = Following.objects.filter(follower=user, followed=self.object).exists()
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

easylearn/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

easylearn/templates/base.html
{% load static i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}easyLearn{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/clean-blog.css'%}" rel="stylesheet">
    
    {% endblock %}

  </head>

  <body>

    <!--<div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">easyLearn</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>-->
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href='{% url 'home'%}'> <img src="{% static 'img/LOGO.svg' %}" id="logo" alt="easyLearn"> </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto ">
             <li class="nav-item">
              <a class="nav-link" href={% url 'about' %}>اتصل بنا</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'users:list' %}>مستخدمين</a>
            </li>
            <li class="nav-item">            
                
                {% if  user.is_authenticated%}
                  <a class="nav-link" href="{% url 'account_logout' %}">تسجيل خروج</a>
                {% else %}
                  <a class="nav-link" href="{% url 'account_login' %}">تسجيل دخول</a>
                {% endif %}
                  
              </li>
              <li class="nav-item">
                  <a class="nav-link" href='{% url 'blog:write' %}'>اكتب مقالاً</a>
                </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home'%}">الرئيسية</a>
            </li>


           
          </ul>
        </div>
      </div>
    </nav>

     <!-- Page Header -->
     <header class="masthead" style="background-image: url('{% static 'img/home-bg.jpg'%}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>{% block page_heading %}easyLearn{% endblock page_heading %}</h1>
              <span class="subheading">{% block page_subheading %}Share your knowledge{% endblock page_subheading %}</span>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    
    {% block footer %}
      <!-- Footer -->
    <footer>
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
              <ul class="list-inline text-center">
                <li class="list-inline-item">
                  <a href="#">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="https://github.com/yazanKabbany/easyLearn/">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
              </ul>
              <p class="copyright text-muted">Copyright &copy; easyLearn 2018</p>
            </div>
          </div>
        </div>
      </footer>
    {% endblock footer %}
      

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      
      <script src="{% static 'js/clean-blog.js' %}"></script>

      {% endblock javascript %}
  </body>
</html>
 